" This is needed so that mvim knows about powerline"
set guifont=Inconsolata\ for\ Powerline:h14

inoremap jj <esc>

nnoremap <leader>ee :wq<cr>
nnoremap <leader>E :wa<cr>:qa<cr>
nnoremap <leader>d :bd<cr>

set laststatus=2
let g:airline_powerline_fonts = 1

nnoremap <2-leftmouse> za


" fine adjust
nnoremap <up> <c-w>1+
nnoremap <down> <c-w>1-
nnoremap <left> <c-w>1<
nnoremap <right> <c-w>1>

" coarse adjust
nnoremap <s-up> <c-w>5+
nnoremap <s-down> <c-w>5-
nnoremap <s-left> <c-w>5<
nnoremap <s-right> <c-w>5>

" Disable stupid backup and swap files - they trigger too many events
" for file system watchers
set nobackup
set nowritebackup
set noswapfile

" Basic cursor movement and deletion keybindings from emacs, for vim.


	" Cocoa/Emacs style insert mode"{{{
	" If on macvim take advantage of option key as meta.
	" TODO: figure out a way to meta-ize option key on other platforms.
	if has("gui_macvim")
		set macmeta
	endif

	imap <C-b> <Left>
	imap <C-f> <Right>
	imap <C-a> <C-o>:call <SID>home()<CR>
	imap <C-e> <End>
	imap <M-b> <C-o>b
	imap <M-f> <C-o>e<Right>
	imap <C-d> <Del>
	imap <C-h> <BS>
	imap <M-d> <C-o>de
	imap <M-h> <C-w>
	imap <C-k> <C-r>=<SID>kill_line()<CR>
	imap <C-p> <Up>
	imap <C-n> <Down>

	" command line mode
	"cmap <C-p> <Up>     "I like the previous command,
	"cmap <C-n> <Down>   "next command funcionality.
	cmap <C-b> <Left>
	cmap <C-f> <Right>
	cmap <C-a> <Home>
	cmap <C-e> <End>
	cmap <M-b> <S-Left>
	cmap <M-f> <S-Right>
	cnoremap <C-d> <Del>
	cnoremap <C-h> <BS>
	cnoremap <M-d> <S-Right><C-w>
	cnoremap <M-h> <C-w>
	cnoremap <C-k> <C-f>D<C-c><C-c>:<Up>

	""Mappings to access buffers (don't use '\p' because a
	"" delay before pressing 'p' would accidentally paste).
	"" \l       : list buffers
	"" \b \f \g : go back/forward/last-used
	"" \1 \2 \3 : go to buffer 1/2/3 etc
	nnoremap <Leader>l :ls<CR>
	nnoremap <Leader>b :bp<CR>
	nnoremap <Leader>f :bn<CR>
	nnoremap <Leader>g :e#<CR>
	nnoremap <Leader>1 :1b<CR>
	nnoremap <Leader>2 :2b<CR>
	nnoremap <Leader>3 :3b<CR>
	nnoremap <Leader>4 :4b<CR>
	nnoremap <Leader>5 :5b<CR>
	nnoremap <Leader>6 :6b<CR>
	nnoremap <Leader>7 :7b<CR>
	nnoremap <Leader>8 :8b<CR>
	nnoremap <Leader>9 :9b<CR>
	nnoremap <Leader>0 :10b<CR>


"DUMP
nnoremap <c-e> :Errors<cr>
nnoremap <c-g> :nohl<cr>
